### ISSUE TITLE
Firebase provider custom data

### ISSUE THREAD

**Issue by andrewhamili** [firebase/firebase-admin-dotnet#103]
Is there a way to get auth provider custom data like the Facebook Access Token?

**Comment by andrewhamili** [comment]
Is there a way to get auth provider custom data like the Facebook Access Token?

**Comment by hiranya911** [comment]
Can you provide more details please? What exactly is your use case?

**Comment by andrewhamili** [comment]
![image](https://user-images.githubusercontent.com/20767537/62992395-cbc31b80-be85-11e9-8045-62e0709dfd57.png)

In Firebase Auth Web, you can obtain Facebook User access token in the authentication result, I would like to get the Facebook User access token on server side instead of requesting it from the client. I haven't tried it yet on Firebase PHP.

**Comment by hiranya911** [comment]
We don't expose this type of client-side operations in the Admin SDK. Admin SDK is expected to be used in server-side/administrative use cases, and therefore should not be directly handling enduser credentials.

**Comment by andrewhamili** [comment]
Yes. I know Firebase Admin SDK is expected to be used server-side. But is it possible to get the facebook User access token usng firebase Admin SDK? I will use it to get some user details on Facebook Graph API.
