### ISSUE TITLE
Getting "not valid registration token" after upgrade to Version 1.8.0

### ISSUE THREAD

**Issue by mduu** [firebase/firebase-admin-dotnet#104]
After upgrading from V 1.7.0 to 1.8.0 I get the following error:

```
The registration token is not a valid FCM registration token
```

on calling `FirebaseMessaging.SendAsync()`. When I downgrade to V 1.7.0 everything works fine again. Same happens if I download a fresh admin JSON.

Here is a part of my code:
```
            ...
            FirebaseApp firebaseApp = FirebaseApp.Create(
                new AppOptions
                {
                    Credential = GoogleCredential.FromJson(firebaseCredentialJson)
                },
                "MY_APP");

            FirebaseMessaging firebaseMessaging = FirebaseMessaging.GetMessaging(firebaseApp);

            string response = await firebaseMessaging.SendAsync(
                CreateMessage(deviceToken, sentMessageId, title, text));
            ...
```

Did I miss any breaking change?

**Comment by hiranya911** [comment]
FCM tokens are never checked/processed in the SDK. Only the FCM backend service can do that. And nothing has changed in the way we send the token to the backend service as far as I know. Can you:

1. try sending a message to some random topic and see if that succeeds?
2. add the following line to your code and share the output?

```
using System;
using Google.Apis.Json;

var message = CreateMessage(deviceToken, sentMessageId, title, text);
Console.WriteLine(NewtonsoftJsonSerializer.Instance.Serialize(message));
```

**Comment by mduu** [comment]
Thanks for your fast response. It was very helpful to know that nothing changed in the way the token gets processed. I debugged my unit-tests further and found that the problem finally was in the changed exception handling and the exception-messages (which is mentioned in the Release notes of 1.8). I aligned our code and now it seems to work with v 1.8.
