### ISSUE TITLE
Adding Users?

### ISSUE THREAD

**Issue by AndrewProteo** [firebase/firebase-admin-dotnet#11]
Hi 

it would be great if the rest of features listed for every other language on the https://firebase.google.com/docs/admin/setup, where available in the library, specifically, creating users?

Thank you

**Comment by hiranya911** [comment]
Eventually we'd like to support all user management capabilities in this SDK. You can help speed things up by providing pull requests.

**Comment by hiranya911** [comment]
Fixed in #67
