### ISSUE TITLE
Support for importing users

### ISSUE THREAD

**Issue by mburumaxwell** [firebase/firebase-admin-dotnet#111]
Is there planned support for importing users similar to node.js?

**Comment by hiranya911** [comment]
Yes, at some point. We welcome pull requests.

**Comment by cucu1** [comment]
Is there any documentation for the admin REST API we can use? or we need too look into implementations in other languages and start from there?

**Comment by hiranya911** [comment]
There's https://firebase.google.com/docs/reference/rest/auth but it might not list all the operations. Looking at one of the other SDKs (Java for instance) is probably the best reference.

**Comment by hiranya911** [comment]
Fixed in #191
