### ISSUE TITLE
How to generate a token?

### ISSUE THREAD

**Issue by petetmailo** [firebase/firebase-admin-dotnet#113]
https://firebase.google.com/docs/admin/setup 
I follow this above page to generate new private key and store key file,
and then set the GOOGLE_APPLICATION_CREDENTIALS environment variable  successfully.
I just only get two file from firebase ,one is "google-services.json" and the other is 'fir-database-fbbf0-firebase-adminsdk-cboyj-a31168588e.json'(private key file)

I want to send message via firebase to client App device,but It always shows the error message "The registration token is not a valid FCM registration token".
I don,t know the parameter of "CreateCustomTokenAsync" Function should fill what ???
I have ever filled my gmail or account name ，but both are invalid.

 ```
       public static async Task SendToTopicAsync()
        {
            try
            {
                    var defaultApp = FirebaseApp.Create(new AppOptions()
                    {
                        Credential = GoogleCredential.GetApplicationDefault(),
                    });

                    var uid = "peter246@gamil.com";
                    string customToken = await 
                    FirebaseAuth.DefaultInstance.CreateCustomTokenAsync(uid);
   
                    var message = new FirebaseAdmin.Messaging.Message()
                    {
                        Data = new Dictionary<string, string>()
                    {
                        { "score", "850" },
                        { "time", "2:45" },
                    },
                        Token = customToken,
                    };

                    string response = await FirebaseMessaging.DefaultInstance.SendAsync(message);
                    Console.WriteLine("Successfully sent message: " + response);

            }
            catch (System.Exception e)
            {
                System.Diagnostics.Debug.WriteLine("Error: " + e);
                throw;
            }

        }
               
        private void Button1_Click(object sender, EventArgs e)
        {
            Task.Run(async () => await SendToTopicAsync());            
       }

```

**Comment by hiranya911** [comment]
Custom tokens are used to authenticate users: https://firebase.google.com/docs/auth/admin/create-custom-tokens

You need FCM device registration tokens to send messages.

Please use StackOverflow for usage questions such as this.
