### ISSUE TITLE
System.ArgumentException: "The default FirebaseApp already exists."

### ISSUE THREAD

**Issue by Sub-Zero-1** [firebase/firebase-admin-dotnet#114]
Hi!

Once I try to initialize a new instance of FirebaseApp in another WPF window a get following message: System.ArgumentException: "The default FirebaseApp already exists."

This message also appears within Android, React etc. and there are solutions for it, but I can't find any solution for .net C#?
So how to avoid this error?

**Comment by hiranya911** [comment]
See how to initialize multiple apps: https://firebase.google.com/docs/admin/setup#initialize_multiple_apps

Please use StackOverflow for usage questions.
