### ISSUE TITLE
click_action for WebpushNotification

### ISSUE THREAD

**Issue by sjahongir** [firebase/firebase-admin-dotnet#120]
How to use click_action with WebpushNotification for web?

Like this?
```
            var message = new MulticastMessage
            {
                Webpush = new WebpushConfig()
                {
                    Notification = new WebpushNotification()
                    {
                        Title = title,
                        Body = body,
                        Icon = icon
                    },
                    FcmOptions = new WebpushFcmOptions
                    {
                        Link = clickAction
                    }
                },
                Tokens = registrationTokens
            };
```

**Comment by hiranya911** [comment]
There's no such option supported in the Webpush Notification spec: https://developer.mozilla.org/en-US/docs/Web/API/notification/Notification

WebpushFcmOptions are documented here: https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/webpush-fcm-options

Please use Stackoverflow for usage questions such as this.

**Comment by Marc-Tanne** [comment]
FirebaseAdmin.Messaging.WebpushFcmOptions link is populated with https:// url and on click of notification, the card simply dismisses, the link is not triggered

**Comment by thisisandreww** [comment]
> FirebaseAdmin.Messaging.WebpushFcmOptions link is populated with https:// url and on click of notification, the card simply dismisses, the link is not triggered

Same issue here, any solution to this? I did see `click_action` with my attached url through the console log but clicking on the notification only dismisses it.

**Comment by evelyn-f-king** [comment]
Also observing this, albeit not with the dotnet API. Anyoine able to figure out what the fix is here?

**Comment by artem-avanesov** [comment]
Same issue
