### ISSUE TITLE
Is there any documentation on how to unit test Firebase SDK?

### ISSUE THREAD

**Issue by radiohe4d** [firebase/firebase-admin-dotnet#122]
I'm trying to write MS Unit tests with Moq framework to test my auth logic with Firebase implementation.

I've tried googling Firebase .Net Unit testing but haven't found anything relevant. 

The Firebase SDK has no Interfaces and all the classes are sealed so its not possible to mock it using Moq.

Aside from wrapping all the methods in their own custom methods (which i successfully did with VerifyIdTokenAsync) as this would be a lot more work than its worth.

**Comment by hiranya911** [comment]
We recommend developers to define their own interfaces for this purpose.

```
interface ITokenVerifier {
  Task<IDictionary<string, object>> VerifyTokenAsync(string token);
}

class FirebaseTokenVerifier : ITokenVerifier {
  // Implementation using FirebaseAdmin.Auth
}

class TestTokenVerifier : ITokenVerifier {
  // Fake implementation for testing
}
```

**Comment by dman777** [comment]
In the discipline of testing, you are never supposed to modify the code to satisfy the test (aside from actually fixing a bug/regression).
