### ISSUE TITLE
Why FirebaseMessagingException ctor is internal?

### ISSUE THREAD

**Issue by neiesc** [firebase/firebase-admin-dotnet#129]
I'm using "Simmy, the monkey for making chaos" http://www.thepollyproject.org/2019/06/27/simmy-the-monkey-for-making-chaos/ for create exceptions and FirebaseMessagingException is not cannot instantiate.

**Comment by hiranya911** [comment]
We keep the public API surface as small as possible. Constructing our exception types in user code is not a typical use case.
