### ISSUE TITLE
Firebase Console - Cloud Messaging Report

### ISSUE THREAD

**Issue by DominikKreuz** [firebase/firebase-admin-dotnet#131]
Hello,

we use this package to send push notifications to Android phones, which is working nicely.
But we can not see any send notification in the report (Firebase console -> Cloud Messaging Report).
Do you have an idea why?

Thanks

**Comment by hiranya911** [comment]
I don't think the notifications sent via the SDK/APIs ever appear on the console. APIs are designed to send large volumes of notifications at scale. Console is designed to send few notifications manually, and it will only display them.
