### ISSUE TITLE
This repository still alive?

### ISSUE THREAD

**Issue by cyraid** [firebase/firebase-admin-dotnet#133]
Being the last update was between months to a year ago.. Is this repository relying on community or are there actual Firebase / Google employees working on this? I might be having second thoughts about using Firebase if the C# support is not alive.

(Are the pull reviews not being looked at?)

**Comment by hiranya911** [comment]
Yes, this repo is looked after. But it has lower priority compared to other languages like Node.js. And we do depend on community contributions for new features.
