### ISSUE TITLE
Verify app tokens or get more information about the app instance that created the token.

### ISSUE THREAD

**Issue by alexsandro-xpt** [firebase/firebase-admin-dotnet#134]
There some API in C# to get information about app instances and verify app tokens or get more information about the app instance that created the token using this API? GET https://iid.googleapis.com/iid/info/<IID_TOKEN>

As mentioned at https://developers.google.com/instance-id/reference/server

**Comment by hiranya911** [comment]
Please file a feature request at https://firebase.google.com/support

None of our SDKs currently expose any API for querying IIDs. It needs to be assessed and treated as a new feature request.

**Comment by alexsandro-xpt** [comment]
@hiranya911 but this feature already exist( GET https://iid.googleapis.com/iid/info/<IID_TOKEN> ) in firebase.

**Comment by hiranya911** [comment]
Yes, but none of our SDKs have this API, and as of today we don't have any plans to add it to the SDKs. So this should be reported to the appropriate team, and assessed as any other new feature request.
