### ISSUE TITLE
setting click_action for iOS notification

### ISSUE THREAD

**Issue by graphicsxp** [firebase/firebase-admin-dotnet#136]
For Android, I set the clickAction of AndroidNotification as below. But how should it be done for iOS ? 

     var msg= new Message()
     {
            Notification = new Notification()
             {
                    Title = message.Title,
                    Body = message.Body,                            
              },
               Data = message.Data,                       
                Android = new AndroidConfig()
                 {
                       Priority = Priority.High,
                       TimeToLive = TimeSpan.FromHours(1),
                        Notification = new AndroidNotification() {  ClickAction = "FCM_PLUGIN_ACTIVITY" 
                   }              
                },                      
                 Token = message.Token
       };

**Comment by hiranya911** [comment]
iOS settings are basically what's documented in the APNs documentation: https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html

Check there and ask around in StackOverflow for how to implement this use case for iOS devices.
