### ISSUE TITLE
Any updates on  multi-tenancy

### ISSUE THREAD

**Issue by mirkarpude** [firebase/firebase-admin-dotnet#149]
Authenticating with multi-tenancy

**Comment by hiranya911** [comment]
Unless we get some contributions from the community, I don't expect it to happen in the near future.

**Comment by moander** [comment]
See #152

**Comment by hiranya911** [comment]
Based on the API signatures we've come for the Java SDK:

```
class AbstractFirebaseAuth {
  // All existing methods in FirebaseAuth
}

class FirebaseAuth : AbstractFirebaseAuth {
  TenantManager TenantManager { get; }
}

class TenantAwareFirebaseAuth : AbstractFirebaseAuth {

}

class TenantManager {
  TenantAwareFirebaseAuth AuthForTenant(string tenantId);
}
```

**Comment by nathan-c** [comment]
It looks like #152  is nearly done but hasn't been touched since Feb. It would be great to get this merged if possible as it is useful functionality to have in the dotnet SDK.
