### ISSUE TITLE
Control Access With Custom Claims

### ISSUE THREAD

**Issue by dominikfoldi** [firebase/firebase-admin-dotnet#15]
We have an ASP.NET Core MVC backend with self hosted Identity Authentication with a custom provider. It is not fully tested and by self hosting it not so secure, so we would like to use an authentication service and Firebase Authentication is the most promising.

BUT the dotnet admin sdk does not have the "Control Access With Custom Claims" feature while role management in our app is core thing. So without this feature we cannot use Firebase Authentication.

Do you have any ETA when it will be added? It is our most urgent feature request.

I saw that you are asking the community to contribute, we really would like to but we are an early stage startup so we do not have the resources to help right now. But if we can successfully integrate Firebase Authentication with our webapp we will contribute in the future definitely!

**Comment by hiranya911** [comment]
Hi @dominikfoldi. We do want to add this API, but right now our resources are spread too thin to attempt it. I'm currently working on implementing FCM support in this SDK. I can start working on this API once that is done. But if you can add the following method to the existing `FirebaseAuth` class, I can get it through the required approval processes.

```
public Task<void> SetCustomUserClaimsAsync(string uid, IReadOnlyDictionary<string, object> claims)
```

The implementation should be pretty straightforward. Just a single REST/HTTP call to the Identity Toolkit API: https://github.com/firebase/firebase-admin-node/blob/master/src/auth/auth-api-request.ts#L421

**Comment by dominikfoldi** [comment]
Hi @hiranya911 , thank you for your fast response. This seems like an easy one. I am going do implement it today.
