### ISSUE TITLE
The datastore operation timed out, or the data was temporarily unavailable

### ISSUE THREAD

**Issue by skjagini** [firebase/firebase-admin-dotnet#157]
Getting "The datastore operation timed out, or the data was temporarily unavailable" with Firestore running in server environment. 

My Environment: .Net Core running in Docker (Linux) in Google Kubernetes  with
Firestore Version: Google.Cloud.Firestore, Version 1.1.0

The issue doesn't happen with Firestore Emulator, it only happens in actual Firestore in GCP. 

The issue is happening only when I query for a property whose actual type is boolean. Querying for non-boolean types works fine in Server Environment. 

Tried connecting to GCP Firestore from Local as well (using Credentials .json file) for debugging puropse and seeing the same issue. 

The code in this case
```
       CollectionReference FoosRef = FirestoreDb.Collection(FooKind);
        Query query = FoosRef.WhereEqualTo("IsGoodFoo", true);
        // QuerySnapshot querySnapshot = await query.Offset(offset).GetSnapshotAsync();
       // Searching for String property works. 
        // Query query = FoosRef.WhereEqualTo("FooName", "p,ezbnR33GU_");
        QuerySnapshot querySnapshot = await query.GetSnapshotAsync();
        DocumentSnapshot documentSnapshot = querySnapshot.Documents.FirstOrDefault();
```

Is there any other way to Query besides the ones I am using. 

Thanks

**Comment by hiranya911** [comment]
Wrong repo. Report at https://github.com/googleapis/google-cloud-dotnet
