### ISSUE TITLE
Support custom Base URL for FirebaseMessagingClient

### ISSUE THREAD

**Issue by fabioalves** [firebase/firebase-admin-dotnet#158]
Hi,

For integration/end-to-end test purposes I would like to set a custom Base URL in FirebaseMessagingClient.

Currently, this value is hardcoded in https://github.com/firebase/firebase-admin-dotnet/blob/7c972d8ab692e84085498f8fa7fea3c150cd0b31/FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessagingClient.cs#L37

This could be configured as a property in FirebaseApp.AppOptions and passed to  FirebaseMessagingClient through Args.

Does this feature make sense? If not, why?

**Comment by hiranya911** [comment]
For unit testing we recommend developers use blackbox testing. `FirebaseMessagingClient` is an internal class, and developers shouldn't be aware of or depend on the implementation details of such classes. The fact that the SDK makes a remote API call is an implementation detail. So define your own interfaces, and create implementations that use the SDK, and separate implementations for testing.

```
interface INotificationSender {
  Task SendAsync(string title, string body);
}

class FirebaseNotificationSender : INotificationSender {
  // implementation using FirebaseMessaging
}

class TestNotificationSender : INotificationSender {
  // implementation for testing
}
```

For end-to-end testing you should probably use a separate staging Firebase project, and run the tests against that project.

If you really want you can control how the SDK makes remote API calls by specifying your own `HttpClientFactory` via `AppOptions`: https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/app-options. 
That way you can direct the outgoing HTTP calls to any endpoint you like. We use this approach for our own unit testing: 

https://github.com/firebase/firebase-admin-dotnet/blob/7c972d8ab692e84085498f8fa7fea3c150cd0b31/FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingClientTest.cs#L82-L107

But typically developers should refrain from relying too much on how the SDK implements its functionality.
