### ISSUE TITLE
createSessionCookie

### ISSUE THREAD

**Issue by andy-hugecalf** [firebase/firebase-admin-dotnet#160]
It looks like createSessionCookie isn't implemented in this dot net SDK - are there any plans to implement it?

**Comment by hiranya911** [comment]
Definitely want to see it implemented at some point. PRs welcome.

**Comment by kevnord** [comment]
+1

**Comment by hotyes** [comment]
+1

**Comment by hiranya911** [comment]
This has been released. See https://firebase.google.com/docs/auth/admin/manage-cookies

**Comment by kevnord** [comment]
Thank you so much! This is great.
