### ISSUE TITLE
Badge not showing on Android 

### ISSUE THREAD

**Issue by HadiHas** [firebase/firebase-admin-dotnet#161]
Hello,

we added the Badge to the android Data payload dictionary but its not showing since it should be as and integer not as string.
is their another way to solve this?

**Comment by hiranya911** [comment]
Please clarify your question. What are you trying to achieve and what have you tried so far (show code samples)?

Data field is usually used to send application-specific data, so sending a badge in it won't do anything.

**Comment by HadiHas** [comment]
Im trying to add the android badge to the notification, im sending the message as MulticastMessage
and want to add the badge number to be received to android when the app is killed. 
how can i achieve that?

What i already did is adding badge to the Message payload {Data} property. but it still not showing.

**Comment by hiranya911** [comment]
There's no such field supported for Android notifications. There's a `badge` field for iOS (APNs) notifications. Is that what you mean?

Here's an exhaustive list of all the options supported by FCM: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message

Can you point out which option you're trying to set?

**Comment by hiranya911** [comment]
Closing due to lack of information
