### ISSUE TITLE
Is this too complicated

### ISSUE THREAD

**Issue by phsumi** [firebase/firebase-admin-dotnet#18]
I landed here because I needed to verify a Firebase ID token, but was surprised that this is so involved (multiple packages to download, creating a FirebaseApp is quite involved). After all, only the FB Project ID is needed to get the full profile through Firebase's own API. So a "cheap" validation could be done by just sending the token with a single HTTP POST to

https://www.googleapis.com/identitytoolkit/v3/relyingparty/getAccountInfo?key=PROJECT_KEY

Anyhow, I ended up writing a validator that just uses .NET's built-in capabilities along with the OpenId specs, which also just requires the project ID. This looks lean enough, but leaves me wondering whether I overlooked anything. If not: Would it be feasible to simplify the setup of the Auth stack?

    public class FirebaseTokenValidator
    {
        private ConfigurationManager<OpenIdConnectConfiguration> configurationManager;

        public string Issuer { get; }
        public string ProjectId { get; set; }

        public FirebaseTokenValidator(string firebaseProjectId)
        {
            ProjectId = firebaseProjectId;
            Issuer = "https://securetoken.google.com/" + firebaseProjectId;
            var metadataAddress = $"{Issuer}/.well-known/openid-configuration";
            var retriever = new OpenIdConnectConfigurationRetriever();
            configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(metadataAddress, retriever);
        }

        
        public async Task<ClaimsPrincipal> ValidateToken(string token)
        {
            OpenIdConnectConfiguration openIdConfig = await configurationManager.GetConfigurationAsync(CancellationToken.None);

            TokenValidationParameters validationParameters = new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidIssuer = Issuer,
                ValidateIssuerSigningKey = true,
                IssuerSigningKeys = openIdConfig.SigningKeys,
                ValidateLifetime = true,
                ValidateAudience = true,
                ValidAudiences = new[] { ProjectId }
            };

            //create token validator (not 100% sure it's thread safe, so better be safe than sorry)
            var tokenHandler = new JwtSecurityTokenHandler();
            ClaimsPrincipal principal = tokenHandler.ValidateToken(token, validationParameters, out var rawValidatedToken);
            
            //to get the token instead:
            //return (JwtSecurityToken)rawValidatedToken;

            return principal;
        }
    }

**Comment by phsumi** [comment]
Thanks for the quick reply! Since I'm not running the app on Google, `FirebaseApp.Create()` crashes on me, and I thought the requirement for additional configuration was a bit involved to get going, when all I needed was the project ID. (Private key generation, file generation and then making it available on the server)

If you think DEV / PROD environments with potentially different Firebase projects / files, which probably also shouldn't be in source control, this becomes non-trivial. I see that this may be required for certain admin tasks, but I prefer to not have to use it when I don't really need to :)

Still happy to see that FB is providing some Code in the .NET space 👍 👍 👍 

Cheers,
Philipp

ps: If you want to map the claims to a `FirebaseToken` - if you look at the commented out snippet, you can see that the validator also return a JWT token instance. This one provides 1:1 mappings for everything in `FirebaseToken` (I think ;) )

https://docs.microsoft.com/en-us/previous-versions/visualstudio/dn464189(v%3Dvs.114)

**Comment by hiranya911** [comment]
You can get application default credentials to work anywhere by setting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. We are increasingly recommending this approach to developers (even when running locally), since it's less code to write, and also it reduces the chance of private keys accidentally getting exposed.

I still don't think it's too much work to set up either ADC or service account credentials. Service account json files are easily downloaded from the Firebase console. I also think using the Admin SDK just to verify ID tokens is not a common scenario. Usually developers would verify the ID token, and then call another Admin SDK API. However, right now the .NET SDK only has a couple of methods, so developers cannot do much else with it. But this will soon change once we release FCM support and other APIs.

Based on your feedback, one optimization I can think of is making the `GoogleCredential` optional in `AppOptions`, and then lazy load it when a component requires it. This enables those who are only using the `VerifyIdToken()` API to do the following:

```
FirebaseApp.Create(new AppOptions()
{
  ProjectId = "my-project-id",
});
await FirebaseAuth.DefaultInstance.VerifyIdTokenAsync(idToken);
```

I suppose this is what you were aiming for?

**Comment by phsumi** [comment]
Creating the `AppOptions` with just the project ID was actually the first thing I tried :)

Not sure it's good developer UX though since this is not self-documenting. And developers might end up with `FirebaseApp`s that work for some things but not for others. So maybe my use case is indeed too exotic (especially if the SDK starts to provide some more features). I'm fine with my current solution and may come back to SDK once I need it.

I'm closing this issue for now - cheers and thanks for taking your time to support me here 🥇 


--
ps:

FYI, https://firebase.google.com/docs/admin/setup doesn't mention the `GOOGLE_APPLICATION_CREDENTIALS` variable, that might be a good addition.

Anyway, reading up on it, it's still about exposing the file on the file system (which I might not have, e.g. in a serverless environment, or would have to handle during CI/CD), so I'd probably rather configure it otherwise to get the file's contents into the SDK (and not worry about storing actual files).

Suggestion: It might be worth mentioning `GoogleCredential.FromJson(string)` and other overloads on https://firebase.google.com/docs/admin/setup#initialize_the_sdk as an alternative to file-based credentials snippet you provide.
