### ISSUE TITLE
IIS 500 error when deployed on server

### ISSUE THREAD

**Issue by sam17896** [firebase/firebase-admin-dotnet#205]
I have integrated this package in my application using .net core 3.1, it working fine on local machine but throwing **500.31 ANCM Failed to Find Native Dependencies** on server. The application works fine without this package. Can anyone please point out which dependencies might be missing from server and if this package support .net core 3.0+. What might be I missing here

**Comment by hiranya911** [comment]
According to Azure documentation https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis:

> The ASP.NET Core Module attempts to start the .NET Core runtime in-process, but it fails to start. The most common cause of this startup failure is when the Microsoft.NETCore.App or Microsoft.AspNetCore.App runtime isn't installed. If the app is deployed to target ASP.NET Core 3.0 and that version doesn't exist on the machine, this error occurs.

I think this issue needs to be debugged and resolved at the deployment level. But if there's anything specific that can be done in this repo, please let us know.
