### ISSUE TITLE
.NET Core 3.1 System.Interactive.Async assembly issues

### ISSUE THREAD

**Issue by TheSpy** [firebase/firebase-admin-dotnet#207]
Trying to run FirebaseAuth ListUsersAsync method an error is thrown 
System.IO.FileNotFoundException: Could not load file or assembly 'System.Interactive.Async, Version=3.2.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.

code snippet

`var e = _firebaseAuth.ListUsersAsync(null).GetAsyncEnumerator();
try
{
    while (await e.MoveNextAsync())
    {
...
    }
}
finally
{
    if (e != null)
    {
        await e.DisposeAsync();
    }
}`

Project has a dependency of a package Google.Cloud.PubSub.V1 ≥ 2.0.0, which is probably using latest Gax

Anyone knows how to fix this?

**Comment by hiranya911** [comment]
Yes, it appears a version conflict between different versions of Gax. The 2.x version of Gax that we depend on has the following dependency:

```
<PackageReference Include="System.Interactive.Async" Version="3.2.0" />
```

This has been removed in the Gax 3.x version. We can start the migration process for latest Gax but it will likely be a while. In the meantime perhaps you can take an explicit dependency on the above assembly and make sure it's available to your app?

**Comment by TheSpy** [comment]
Thanks for reply.

I have tried that, unfortunately another error is thrown saying

System.NotImplementedException: The method or operation is not implemented.
   at Google.Api.Gax.PagedAsyncEnumerable`2.GetAsyncEnumerator(CancellationToken cancellationToken)

**Comment by hiranya911** [comment]
Can you try raising this at https://github.com/googleapis/gax-dotnet?

Given that the issue is caused by their libraries, they might have known workarounds. Only other immediate solution I can think of is downgrading your other PubSub dependency to something that uses Gax 2.x

**Comment by TheSpy** [comment]
Downgrading to an older PubSub version did help. This is good enough until client migrated to latest GAX.

Thanks for you help.

**Comment by liongkj** [comment]
> Downgrading to an older PubSub version

Hi @TheSpy , do you mind explaining how to downgrade to older pubsub version? I tried google but i still have no idea

**Comment by liongkj** [comment]
@hiranya911 Could you please give me some pointers. I am stuck at this for weeks now,

**Comment by hiranya911** [comment]
@liongkj you will have to go through your dependencies, and downgrade anything that depends on Gax 2.0.

**Comment by Bartizan** [comment]
as far as I can see it is resolved and could be closed. Thanks

**Comment by TheSpy** [comment]
I confirm that a release https://github.com/firebase/firebase-admin-dotnet/releases/tag/v2.0.0  has this issue resolved.
Thank you!
