### ISSUE TITLE
Background Notification not being sent to iOS app

### ISSUE THREAD

**Issue by crash-her** [firebase/firebase-admin-dotnet#216]
When I execute the below code my app does not get the background notification but the batchResponse is a success. Before switching to Firebase we were using Apples APNS protocols to trigger the background notifications and it works flawlessly. 

```
var fireMessages = new List<FireMessage>()
{
    new FireMessage()
    {
        Data =  new Dictionary<string, string>(){{"type","update"}},
        Token = token,
        Apns = new ApnsConfig
        {
            Headers = new Dictionary<string, string>
            {
                {"apns-push-type", "background"},
                {"apns-priority", "5"}
            },
            Aps = new Aps
            {
                ContentAvailable = true
            }
        }
    }
};

var firebaseApp = FirebaseApp.GetInstance(instanceName);

var batchResponse = await FirebaseMessaging.GetMessaging(firebaseApp).SendAllAsync(fireMessages);
```

the generated body is
```
{
    "message": {
        "token": "fO7t3fyX-k3sgEk5Mtv6O-:...",
        "data": {
            "type": "activity_updates"
        },
        "apns": {
            "headers": {
                "apns-push-type": "background",
                "apns-priority": "5"
            },
            "payload": {
                "aps": {
                    "content-available": 1
                }
            }
        }
    },
    "validate_only": false
}
```

**Comment by hiranya911** [comment]
Are there any errors indicated in the returned `BatchResponse`?

**Comment by crash-her** [comment]
No

Thanks
-Mat

**Comment by hiranya911** [comment]
Please reach out to Firebase Support and provide your project ID and token information. They can help you sort it out. If there are no errors in the SDK-end that means the message was successfully handed off to FCM backend service for delivery.

**Comment by crash-her** [comment]
when i use the legacy API i send it a JSON of 

```{
  "data":{
      "type":"activity_updates"
  },
  "priority": "high",
  "content_available": true,
  "to":"dCw-..."
}``

that works

**Comment by Gekidoku** [comment]
I have the same issue and with the legacy api being depreciated soon this should really be fixed.
It works on android for me. but on ios i dont recieve a message unless i also include the notification field.

**Comment by Gekidoku** [comment]
https://dotnetfiddle.net/iwIGCu Here is how im sending the message
