### ISSUE TITLE
Runtime compilation error (Razor View)

### ISSUE THREAD

**Issue by TCGV** [firebase/firebase-admin-dotnet#23]
Not sure if this is a real issue, or just a (package dependency) compatibility problem.

I encountered the following runtime compilation error (Razor View) after adding FirebaseAdmin to my ASP .NET MVC 5 project:
- https://stackoverflow.com/questions/22822406/build-error-you-must-add-a-reference-to-system-runtime/54405782#54405782

It was actually caused by the "System.Collections.Immutable" package that triggered warning CS1685 (type defined in multiple assemblies).

I forked the repository and removed the "System.Collections.Immutable" dependency, which solved my issue:
- https://github.com/TCGV/firebase-admin-dotnet/commit/85bef758a8adcc81b801087840f89c56f50e24f8

Decided to open this issue to let you know. Thanks!

**Comment by hiranya911** [comment]
@TCGV thanks for reporting this. It would be helpful if you can also add the exact error message you got to this issue. 

As I understand from https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1685 this happens due to conflicting usages of assemblies. I'll keep this open so others running into similar issues can also post their feedback.

**Comment by TCGV** [comment]
Hi @hiranya911! Below is the detailed error message:

> warning CS1685: The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in multiple assemblies in the global alias; using definition from 'c:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll'
>
>c:\Users\Admin\Software Development\source-control\Binaries\Publish\WebApp\Views\Account\Index.cshtml(35,20): error CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
>
>c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\meseems.webapp\68e2ea0f\8c5ee951\assembly\dl3\52ad4dac\84698469_3bb3d401\System.Collections.Immutable.DLL: (Location of symbol related to previous error)

**Comment by Wilson-Lim** [comment]
Is there a fix other than forking out ?

**Comment by sonyisda1** [comment]
See this [SO posting](https://stackoverflow.com/a/38603514/731081).  Basically you need to add the assembly reference:
`<add assembly="System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />`

**Comment by hiranya911** [comment]
I'm going to close this as we don't see any specific action items for this repo. Feel free to comment if something needs to change in the codebase.
