### ISSUE TITLE
IOs notification missing fields

### ISSUE THREAD

**Issue by slorinc1** [firebase/firebase-admin-dotnet#258]
Hi,
I am migrating from the legacy API to the V1 version and previously I was using rest call, now I am switching to the .net sdk. However I noticed that in the notification I cannot add the field I need in case of IOs,
The previous payload was 
` new
                    {
                        data = payload,
                        notification = new { sound = "default", body = msg, click_action = "SOME_ACTION" },
                        to = tagID
                    }`

The current notification only supports title, body, iamgeUrl.
How can I use the sdk for this use case for IOs? 
Thanks in advance!

(If I create a PR when can it be released?)

**Comment by hiranya911** [comment]
Notification in v1 backend API only supports those 3 fields: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Notification

Other IOS specific fields must be set via APNSConfig: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#ApnsConfig

Corresponding .NET API: https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/apns-config

**Comment by Gekidoku** [comment]
We do need some of these fields. and even though their API documentation doesnt list this FCM does in fact support the android specific field Click_Action in the notification https://stackoverflow.com/questions/39137727/how-to-send-actionable-notifications-to-ios-with-firebase
