### ISSUE TITLE
Problem with your Google.Apis.Json.NewtonsoftJsonSerializer.Serialize(object obj)

### ISSUE THREAD

**Issue by trinhnghia** [firebase/firebase-admin-dotnet#260]
I have a problem with your Google.Apis.Json.NewtonsoftJsonSerializer.Serialize(object obj). It not get the Newtonsoft.Json.JsonProperty(string name) (Example: [JsonProperty("token")]) . It always return the name of property (Example "Token"). If I change to use Newtonsoft.Json.JsonConvert.SerializeObject(object obj) it return right. 
Please fix it! Thanks

**Comment by hiranya911** [comment]
Wrong repo. Please report at https://github.com/googleapis/google-api-dotnet-client/tree/master/Src/Support/Google.Apis.Core/Json
