### ISSUE TITLE
conflict between FirebaseAdmin 1.17.1 and Google.Cloud.Firestore 2.2.0

### ISSUE THREAD

**Issue by MHDuke** [firebase/firebase-admin-dotnet#264]
there is a conflict arises when I include both `FirebaseAdmin 1.17.1` and `Google.Cloud.Firestore 2.2.0` packages.

`FirebaseAdmin 1.17.1` package has a dependency on `Google.Api.Gax 2.7.0`.
`Google.Cloud.Firestore 2.2.0` package has a dependency on `Google.Api.Gax 3.2.0`.

When installing both packages side by side in one .Net project, the `FirebaseAdmin 1.17.1` automatically grabs the higher version `Google.Api.Gax 3.2.0` which causes compile errors. specifically because the use of `Microsoft.Bcl.AsyncInterfaces` in `Google.Api.Gax 3.2.0` while using `System.Interactive.Async` in `Google.Api.Gax 2.7.0`

I guess this issue belongs here because `FirebaseAdmin` is not restricting `Google.Api.Gax` dependency to version `2.7.0`

> When installing `FirebaseAdmin 1.17.1` solely.
![google api gax](https://user-images.githubusercontent.com/37734594/96507965-c3dfd380-120e-11eb-839d-df173d6a8dbf.png)

> When installing both packages
![google api gax_together](https://user-images.githubusercontent.com/37734594/96508009-d3f7b300-120e-11eb-9ce8-c1acce073b2f.png)

**Comment by TheSpy** [comment]
I think it's the same issue as https://github.com/firebase/firebase-admin-dotnet/issues/207

**Comment by MHDuke** [comment]
as per [microsoft documentation](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges), adding square brackets around package version number should solve the issue. for example:
`<PackageReference Include="Google.Api.Gax" Version="[2.7.0]" />`

**Comment by hiranya911** [comment]
Our Gax dependency is due for an upgrade (see #251). I think the same PR should address this issue as well.

**Comment by hiranya911** [comment]
Also I wish there was a way in .NET to restrict a dependency to specific major version (like NPM does for Node.js). It seems this can be achieved by specifying versions as `[2.0.0, 3.0.0)` (which means any 2.x.x version but not. 3.x.x). 

See https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges

**Comment by MHDuke** [comment]
`Google.Api.Gax.Rest 3.2.0` should solve the issue. And yes, this is exactly what you might go for `[2.0.0, 3.0.0)`. inclusive minimum, and exclusive maximum. I learnt some good stuff today. thanks.
