### ISSUE TITLE
IAsyncEnumerable<T> exists in both System.Interactive.Async and System.Runtime 

### ISSUE THREAD

**Issue by sumonkumardas** [firebase/firebase-admin-dotnet#265]
When I tried to use  IAsyncEnumerable<T> from System.Collection.Generic and FiredaseAdmin(1.17.1) then it shows conflict.

![image](https://user-images.githubusercontent.com/13537430/96690194-2ec31300-13a5-11eb-90b7-6b59293f4423.png)

![image](https://user-images.githubusercontent.com/13537430/96690455-86fa1500-13a5-11eb-81e5-2f18c5cff49a.png)

Target platform -- .net core 3.1
Project Type -- .net standard class library

**Comment by hiranya911** [comment]
Resolved with the v2 release.
