### ISSUE TITLE
Does this work with the emulators

### ISSUE THREAD

**Issue by jculverwell** [firebase/firebase-admin-dotnet#274]
Just wondering if this works with the firebase emulators?

**Comment by lahirumaramba** [comment]
Thank you for reaching out! We currently do not have the emulator support in the Admin .NET SDK. I will mark this as a feature request for now.

**Comment by jculverwell** [comment]
Thanks for the quick response and thank you for adding this as a feature request

**Comment by samtstern** [comment]
@jculverwell as mentioned in the README [contributing section](https://firebase.flutter.dev/docs/storage/usage#downloading-files) this library is _mostly_ driven by open source contributions from external developers.  So while I definitely think it would be great to have emulator support here, right now we (the emulator team) don't have plans to add it ourselves.

If you're interested in contributing support for one of the emulators let me know! We could discuss the best route forward and then I could review the Pull Request.

**Comment by floppydisken** [comment]
I'd love for this to happen as well. And I'm willing to help. However I'm quite unaware of the scope.

**Comment by floppydisken** [comment]
I've started a pull request for this purpose https://github.com/firebase/firebase-admin-dotnet/pull/289. Starting with Authententication emulation support

**Comment by hiranya911** [comment]
I've merged #289 into a new `auth-emulator` branch. Remaining features to be implemented include:

* `CreateCustomTokenAsync()`
* `VerifyIdTokenAsync()`

**Comment by floppydisken** [comment]
> * `CreateCustomTokenAsync()`

I wouldn't mind taking care of this. Can you point me in the direction of some reference material or be more specific as to what is missing exactly?

**Comment by hiranya911** [comment]
Thanks @floppydisken. I've already done most of the work to support that. Just waiting for #291 to get through first.

**Comment by hiranya911** [comment]
Auth emulator support included in the last release.
