### ISSUE TITLE
Feature Request: Batch Subscribe/Unsubscribe to multiple topics

### ISSUE THREAD

**Issue by naveedahmed1** [firebase/firebase-admin-dotnet#275]
### Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 2.0.0
  * Firebase Product: FCM
  * .NET version: applies to all version
  
### Here's a feature request

I believe this is a common use case that an app/website user is normally subscribed to multiple topics.

The current version of sdk provides a method to subscribe to topics `SubscribeToTopicAsync` but for multiple topics subscription, we have to call this method multiple times which results in multiple http requests. 

Therefore I wanted to request a feature that allow developers to batch subscribe a user to multiple topics.

Similarly, a method to batch unsubscribe a user from multiple topics in single request.

**Comment by hiranya911** [comment]
I don't think we have any backend APIs for this functionality today. You should probably file a feature request at https://firebase.google.com/support/troubleshooter/report first.

@chong-shao wdyt?

**Comment by naveedahmed1** [comment]
Thank you @hiranya911, I just submitted a feature request for support of this feature in backend API.

**Comment by chong-shao** [comment]
Yes submitting a feature request would be the best option. Thanks!

**Comment by theobouwman** [comment]
Is it already possible to subscribe to more topcis?
