### ISSUE TITLE
Don't works via proxy

### ISSUE THREAD

**Issue by Krey81** [firebase/firebase-admin-dotnet#277]
Then i set custom HttpClientFactory in AppOptions with Proxy this works only for internal connections to https://fcm.googleapis.com. Connections to https://oauth2.googleapis.com ignore my handler and keep going directly without proxy. 
The problem can be solved by setting the OS environment variable https_proxy, but it breaks my other functionality.
Please correct the code so that the FirebaseApp supports the custom handler in full and not partially.

Thanks.

**Comment by hiranya911** [comment]
`GoogleCredential` API is part of a different library, and you need to configure `HttpClientFactory` for it separately. Unfortunately the code necessary for this is somewhat complex at the moment. 

See the examples shown at https://github.com/googleapis/google-api-dotnet-client/issues/1547 and https://medium.com/google-cloud/accessing-google-cloud-apis-though-a-proxy-fe46658b5f2a.
