### ISSUE TITLE
Add Device group management

### ISSUE THREAD

**Issue by DamienDoumer** [firebase/firebase-admin-dotnet#278]
Firebase permits users to manage devices via Device group messaging.
This can be very useful for developers willing to build a backend that sends notifications to users with multiple mobile devices. 
[Here is what we can](https://firebase.google.com/docs/cloud-messaging/android/device-group) do with device group messaging via HTTP calls. Having a C# dotnet implementation will be very useful.

I made a little library that leverages the firebase admin sdk for dotnet and implements device group messaging in it. [You can find it here](https://github.com/coolc0ders/FirebaseCloudMessagingWithDotnet), could my work be integrated into this library?
Implementing this feature doesn't seem very difficult, so I'm wondering, Is there a reason why device group messaging is not available in the admin SDK ?

**Comment by chong-shao** [comment]
Group feature is going to be replaced by the topics feature hence we decided to not support group management in Admin SDK. 

More context can be found in https://github.com/firebase/firebase-admin-node/issues/173

**Comment by DamienDoumer** [comment]
@chong-shao  thanks for the info. Please, how can we keep ourselves aware of when the new Topics feature will be available ?

**Comment by chong-shao** [comment]
Hi @DamienDoumer, we don't have a specific timeline for that for now. A newly launched feature will be mentioned in FCM API documentation https://firebase.google.com/docs/cloud-messaging/send-message and Admin SDK release notes.

**Comment by DamienDoumer** [comment]
Ok, noted.

**Comment by indorock** [comment]
What a weird decision, especially considering the [actual docs](https://firebase.google.com/docs/cloud-messaging/js/topic-messaging) literally recommend us to NOT use Topics and only use device groups when sending to multiple devices for a user.
