### ISSUE TITLE
Field not found: 'Initializer.DefaultHandleUnsuccessfulResponseFunc' issue when calling FirebaseApp.Create

### ISSUE THREAD

**Issue by atagaew** [firebase/firebase-admin-dotnet#284]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows Server 2016
  * Firebase SDK version: 
  * Firebase Product: _____ (auth, database, storage, etc)
  * .NET version: .Net Framework 4.6.2
  * OS: Windows Server

### [REQUIRED] Step 3: Describe the problem
An application can't  initialize FirebaseApp instance with error

System.MissingFieldException: Field not found: 'Initializer.DefaultHandleUnsuccessfulResponseFunc'.
   at FirebaseAdmin.Util.RetryOptions.get_Default()
   at FirebaseAdmin.Messaging.FirebaseMessagingClient.Create(FirebaseApp app)
   at FirebaseAdmin.Messaging.FirebaseMessaging..ctor(FirebaseApp app)
   at FirebaseAdmin.Messaging.FirebaseMessaging.<>c__DisplayClass5_0.<GetMessaging>b__0()
   at FirebaseAdmin.FirebaseApp.GetOrInit[T](String id, ServiceFactory`1 initializer)
   at EventNotifier.FirebaseNotifier.FirebaseMessageSender.<DoSend>d__4.MoveNext() in C:\gitlab-runner\builds\4bEsN_fP\0\fl\EventNotifier\EventNotifier\FirebaseNotifier\FirebaseMessageSender.cs:line 66

#### Steps to reproduce:
I have an application that sends notifications via Firebase
The code that I have perfectly working on Windows 10 Home edition and on another Windows Server 2016 
On the current server I have issue 'Field not found: 'Initializer.DefaultHandleUnsuccessfulResponseFunc'' when it's executing line "FirebaseApp.Create" (see the code below)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
 public class FirebaseAppClient
    {
        private static readonly object _syncRoot = new object();
        private static FirebaseAppClient _instance;

        private FirebaseAppClient()
        {
            if (FirebaseApp.DefaultInstance == null)
            {
                FirebaseApp = FirebaseApp.Create(new AppOptions()
                {
                    Credential =
                        GoogleCredential.FromJson(
                            JsonConvert.SerializeObject(new FirebaseConfigProvider().GetConfiguration())),
                });
            }
            else
            {
                FirebaseApp = FirebaseApp.DefaultInstance;
            }
        }

        public static FirebaseAppClient GetInstance()
        {
            if (_instance == null)
            {
                lock (_syncRoot)
                {
                    _instance = new FirebaseAppClient();
                }
            }

            return _instance;
        }

        public FirebaseApp FirebaseApp { get; private set; }
    }
```

**Comment by hiranya911** [comment]
Check you Google API client dependencies? The property in question comes from here: https://github.com/googleapis/google-api-dotnet-client/blob/aa4f841973671775f6e4ad9ab7a5052bcade0898/Src/Support/Google.Apis.Core/Http/BackOffHandler.cs#L60-L62

Should be available on all recent versions of the dependency. We currently have a hard dependency on `Google.Apis.Auth` v1.49.0, which should pull in `Google.Apis.Core` v1.49.0 transitively.

**Comment by atagaew** [comment]
Thank you.
I've check the dependencies and they are looking ok, see attached file

[EventNotifier.csproj.txt](https://github.com/firebase/firebase-admin-dotnet/files/5876546/EventNotifier.csproj.txt)

This implementation is working perfectly on another server. Even if I just copy project dlls to another server it working well. What else can be the issue ?

Thank you!

**Comment by hiranya911** [comment]
Difficult to tell other than it's some strange dependency binding issue at runtime. Perhaps you should try compiling some source similar to the following and see what sort of error messages you get back. Hopefully that will shed more light on the problem. Basically, force the error to occur at compile time instead of runtime.

```csharp
using Google.Apis.Http;

public class Issue
{
    public static readonly Func<HttpResponseMessage, bool> TestFunc =
                BackOffHandler.Initializer.DefaultHandleUnsuccessfulResponseFunc;
}
```

**Comment by atagaew** [comment]
The issue resolved. The reason was "DLL Hell" issue of identifying right version of System.Net.Http.dll used by Google.Apis.Auth package.

The solution described here -https://stackoverflow.com/questions/65698676/asp-net-firebaseadmin-fails-to-initilize-system-missingfieldexception/65918156#65918156

**Comment by hiranya911** [comment]
Might worth reporting an issue against the Google API client, and see if they can do something about that. Perhaps, they should define a specific version for the `System.Net.Http` dependency: https://github.com/googleapis/google-api-dotnet-client/blob/aa4f841973671775f6e4ad9ab7a5052bcade0898/Src/Support/Google.Apis.Core/Google.Apis.Core.csproj#L42-L44
