### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by nixj14** [firebase/firebase-admin-dotnet#30]
This API does not work when behind a corporate proxy.  If you were to expose the HttpClientFactory creation in FirebaseMessaging.cs as a parameter it would allow proxies to be supported.  If I get time, I'll create  a pull-request illustrating the idea.

**Comment by hiranya911** [comment]
I believe the right solution is to inject `HttpClientFactory` via `AppOptions` (similar to how the Java SDK works).

**Comment by nixj14** [comment]
See https://github.com/firebase/firebase-admin-dotnet/pull/34

**Comment by nixj14** [comment]
Here's an implementation of HttpClientFactory that supports proxies (for anyone who finds this issue):

`using System.Net;
using System.Net.Http;
using Google.Apis.Http;

namespace FirebaseAdmin.Messaging
{
    /// <summary>
    /// Extension of Google's Default implementation of IHttpClientFactory, used to supply Proxy
    /// information.
    /// <see href="https://kzhendev.wordpress.com/2015/04/28/accessing-google-apis-through-a-proxy-with-net/">Example 1: Google</see>.
    /// <see href="https://github.com/tmenier/Flurl/blob/dev/src/Flurl.Http/Configuration/DefaultHttpClientFactory.cs">Example 2: Flurl Impl</see>.
    /// </summary>
    public sealed class ProxyHttpClientFactory : HttpClientFactory
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProxyHttpClientFactory"/> class.
        /// </summary>
        /// <param name="proxy">The proxy to use.</param>
        public ProxyHttpClientFactory(IWebProxy proxy)
        {
            this.Proxy = proxy;
        }

        /// <summary>
        /// Gets or sets the Proxy.
        /// </summary>
        private IWebProxy Proxy { get; set; }

        /// <inheritdoc/>
        protected override HttpMessageHandler CreateHandler(CreateHttpClientArgs args)
        {
            return new HttpClientHandler
            {
                Proxy = this.Proxy,
                UseProxy = true,
            };
        }
    }
}`

**Comment by hiranya911** [comment]
Fix in #34 is released now.
