### ISSUE TITLE
Limit registration tokens of sending multicast message

### ISSUE THREAD

**Issue by 20092738** [firebase/firebase-admin-dotnet#304]
Document of MulticastMessage shows that we can send multicast message up to [500 registration tokens](https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/multicast-message)
However in my program show error following log when tried to send over 100 registration token
`Tokens must be non-null and contain at most 100 tokens.`
(My FirebaseAdmin v1.9.1)

So, which is correct number of limit registration token?

**Comment by hiranya911** [comment]
Limit was increased to 500 in v2.0.0 release.

**Comment by 20092738** [comment]
@hiranya911  thank you so much!
I've solved this problem by upgrading library to v2
