### ISSUE TITLE
Which URLs & ports should be open for the package to work?

### ISSUE THREAD

**Issue by tinonetic** [firebase/firebase-admin-dotnet#307]
Hi,

What URLs does the SDK require to work.

Our backend is sitting behind a web application firewall and a proxy server. So we need to know what to configure on it.

Sorry if it's in the documentation, but I do not see any reference in it. Please do add it if it isn't there already.

I have managed to pick the following. I hope I am write. Please confirm or correct me.

https://oauth2.googleapis.com:443
https://fcm.googleapis.com:443

Kind Regards,
Tino

**Comment by hiranya911** [comment]
If you're only using the FCM send API, then above 2 endpoints are enough. Other services/APIs call additional endpoints. Good call on documenting this somewhere. @egilmorez thoughts?

**Comment by tinonetic** [comment]
We configured firewall rules to allow everything going to *.googleapis.com:443

Works well, and would cover future integrations
