### ISSUE TITLE
Need Documentaion: How can print the access token   

### ISSUE THREAD

**Issue by code4muktesh** [firebase/firebase-admin-dotnet#314]
Is there anyway to extract access token sothat can directly hit the api using post man

**Comment by lahirumaramba** [comment]
The Admin SDK uses https://github.com/googleapis/google-api-dotnet-client
I believe you should be able to access the token from the `Credential` instance.
For example:
```
GoogleCredential.GetApplicationDefault().GetAccessTokenForRequestAsync()
```

In the future, please use StackOverflow for usage questions. Thanks!
