### ISSUE TITLE
non-android TimeToLive (for message lifetime)?

### ISSUE THREAD

**Issue by asaalberglodasoft** [firebase/firebase-admin-dotnet#336]
The 'TimeToLive' property is within the AndroidConfig sub-object of message

https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/android-config#class_firebase_admin_1_1_messaging_1_1_android_config

Is that the same as the 'time_to_live' flag described here?

https://firebase.google.com/docs/cloud-messaging/concept-options#lifetime 

If not, how do I set that 'time_to_live' flag using this API?

**Comment by chong-shao** [comment]
Hi @asaalberglodasoft , yes, the "time_to_live" described in the two pages are the same concept.
