### ISSUE TITLE
Setting "CollapseKey" not works as expected

### ISSUE THREAD

**Issue by hgndgn** [firebase/firebase-admin-dotnet#344]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Android 11
  * Firebase SDK version: FirebaseAdmin 2.3.0
  * Firebase Product: admin (auth, database, storage, etc)
  * .NET version: 6.0.100
  * OS: Android 11

### [REQUIRED] Step 3: Describe the problem

I have react-native app, where I am using firebase to get push notifications.

Using C# Admin SDK I am sending a push notification with a `CollapseKey` to my device. When I print the remote message in my `BackgroundMessageHandler` the collapse key is always `com.myapp`, despite I am setting it in the message. Should I do something else?

Below is the message object that I am sending.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
new Message()
{
    Token = payload.PushToken,
    Data = payload.Data,
    Android = new AndroidConfig()
    {
        Notification = new AndroidNotification()
        {
            Title = payload.Notification.Title,
            Body = payload.Notification.Body,
        },
        Data = payload.Data,
        Priority = Priority.High,
        CollapseKey = "my-collapse-key"
    }
};
```

**Comment by chong-shao** [comment]
Hello, this is working as intended. According to the public documentation https://firebase.google.com/docs/cloud-messaging/concept-options#collapsible_and_non-collapsible_messages, "Notification messages are always collapsible and will ignore the collapse_key parameter."
