### ISSUE TITLE
FCM: support for multiple recipients/batching

### ISSUE THREAD

**Issue by kentcb** [firebase/firebase-admin-dotnet#35]
I need to send notifications to multiple users. I was surprised to find that this SDK does not support multiple recipients/batching, even though the Java and Node SDKs do. See [here](https://firebase.google.com/docs/cloud-messaging/send-message#send_messages_to_multiple_devices), for example.

Why is this? And what is the recommendation for those, like me, who need to send notifications to many users? I am currently getting by with [the legacy API](https://firebase.google.com/docs/cloud-messaging/send-message#send_messages_using_the_legacy_app_server_protocols), but had hoped to switch to the new. I expected the SDK would make things simple, but now it seems I can't even use it.

**Comment by hiranya911** [comment]
Batch support was just released last week. We always release new APIs in Node.js first (and sometimes in Node.js and Java), and then gradually port them to other languages. We don't have the bandwidth to maintain feature parity across all languages. So some SDKs will always lag behind Node.js. In case of the .NET SDK we are really relying on our open source community to develop and contribute new APIs. From our README file:

> Development of the Admin .NET SDK is mostly driven by our open source community. We welcome and encourage contributions from the developer community to further improve and expand this project. If you would like a new feature or an API added to this SDK, please file an issue and provide a pull request. You can use other Firebase Admin SDKs as a reference on how certain features should be implemented

We will eventually bring all the missing APIs to this SDK. But it's on a "best effort" basis, and we cannot commit to any timeline. If you need something done urgently, please consider contributing it.

**Comment by kentcb** [comment]
@hiranya911 I'm a good way into a PR but have hit a snag. I could use some guidance.

I'd like to use [BatchRequest](https://developers.google.com/api-client-library/dotnet/reference/1.10.0/classGoogle_1_1Apis_1_1Requests_1_1BatchRequest) to implement the `FirebaseMessagingClient.SendAllAsync` method. However, unlike the Java version of `BatchRequest`, it requires an `IClientService` to construct it. I can't see any implementation of `IClientService` for FCM, and I can't see one generated [over here](https://github.com/googleapis/google-api-dotnet-client/tree/334b2024b78a636af7f997fb344043322c9e379b/Src/Generated) either.

Am I barking up the wrong tree? Will I have to forgo the `BatchRequest` and implement batching myself (somehow)?

**Comment by kentcb** [comment]
I guess I could write my own based on [the TypeScript one](https://github.com/firebase/firebase-admin-node/blob/master/src/messaging/batch-request.ts), but please let me know if you think that's the right approach.

**Comment by hiranya911** [comment]
It certainly would be nice if we can reuse that bit of code. Perhaps we can create a bare minimum implementation of `IClientService` by extending the `BaseClientService` class?

**Comment by kentcb** [comment]
@hiranya911 Do you know of any docs for the batch HTTP endpoint? I can't find anything and it's making this process far more difficult.

**Comment by kentcb** [comment]
I opened #36 as draft because I literally have no idea what I'm doing with respect to client service/client service request in particular.

**Comment by hiranya911** [comment]
Hi @kentcb. Documentation for this endpoint is still a work in progress. But I believe you're on the right track (I just skimmed through what you have coded so far, and also looked at how the `BatchRequest` class itself is implemented). 

In your `FCMClientServiceRequest` class do the following:

* Set HttpMethod to POST.
* Set RestPath to `/v1/projects/{0}/messages:send` (the same path as the `SendAsync()` API). `{0}` should be replaced by the project ID. See how the `FirebaseMessagingClient` calculates the `sendUrl` attribute. Feel free to refactor that bit as necessary, so you can reuse it.
* Override the `GetBody()` method to return a `SendRequest` object.

Then in your `FCMClientService` class do the following:

* Set BaseUri to `https://fcm.googleapis.com`

These settings should result in the correct batch request from being made. At least should get us pretty close to the intended result.

**Comment by kentcb** [comment]
Thanks. FYI, have made good progress and have a dry-run basically working (though largely untested). I'll spend some more time on this tomorrow.

**Comment by kentcb** [comment]
@hiranya911 Any idea how I can integration test the new `SendMulticastAsync` API when it requires tokens (not topics)? If I pass in dummy tokens, I get "The registration token is not a valid FCM registration token". If I pass in a real token (but for a different app) then I get "The caller does not have permission".

I also can't find any reference to Firebase "test" tokens that can be used with dry runs.

**Comment by hiranya911** [comment]
This was released a short while ago. Thanks @kentcb for the contribution: https://firebase.google.com/support/release-notes/admin/dotnet
