### ISSUE TITLE
[FR] Add Direct_Boot_OK to AndroidConfig()

### ISSUE THREAD

**Issue by CatrinaFitabase** [firebase/firebase-admin-dotnet#382]
Following the instructions to include "direct_boot_ok" : true in the message request body: 

https://firebase.google.com/docs/cloud-messaging/send-message#c_3

Some packages such as Python Admin SDK have a direct boot parameter: 
https://firebase.google.com/docs/reference/admin/python/firebase_admin.messaging

However, is the .NET SDK does not:
https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/android-config

Is there another location to pass this parameter or will this be added later?

**Comment by jonathanedey** [comment]
This is fixed in https://github.com/firebase/firebase-admin-dotnet/pull/431 and available in [v3.1.0](https://github.com/firebase/firebase-admin-dotnet/releases/tag/v3.1.0)
