### ISSUE TITLE
IOS device not receive notification

### ISSUE THREAD

**Issue by MonikaGulve** [firebase/firebase-admin-dotnet#383]
message = new MulticastMessage()
    {
        Tokens = registrationTokens,
        Notification = new FirebaseAdmin.Messaging.Notification()
        {
            Body = body,
            Title = title

        },
        Data = new Dictionary<string, string>()
{
    {"title", title},
    {"body", body},
}.Concat(dix).ToDictionary(x => x.Key, x => x.Value),
        Apns = new ApnsConfig()
        {
            Aps = new Aps()
            {
                Sound = "default",
            }
        }
    };

**Comment by MonikaGulve** [comment]
For android getting notifications but for ios not getting any notification even though SendMulticastAsync shows success for ios

**Comment by chong-shao** [comment]
This seems to be a message delivery issue. For further investigations please file a ticket to Firebase support https://firebase.google.com/support/troubleshooter/contact where you can provide more information for us to debug the issue. Thanks!
