### ISSUE TITLE
Error message on APS notifications

### ISSUE THREAD

**Issue by albernhagen** [firebase/firebase-admin-dotnet#39]
Hello - When I'm sending APS notifications, I'm getting an error as follows:

```Response status code does not indicate success: 400 (BadRequest)
{
  "error": {
    "code": 400,
    "message": "Value of [aps] must be a non-empty dictionary.",
    "errors": [
      {
        "message": "Value of [aps] must be a non-empty dictionary.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

I am sending a message that does have [aps] populated.  Is there something else I could be missing?

```            
           var fcmMessage = new Message()
            {
                Token = address,
                Apns = new ApnsConfig()
                {
                    Aps = new Aps()
                    {
                        ContentAvailable = contentAvailable,
                        Badge = badge,
                        Sound = sound,
                    },
                },
            };

            if (data != null && data.Count > 0)
            {
                fcmMessage.Apns.CustomData = data;
            }

            if (!silentOnApns)
            {
                fcmMessage.Notification = new Notification()
                {
                    Title = title,
                    Body = message,
                };
            }

            var firebaseMessaging = FirebaseMessaging.GetMessaging(this.firebaseApp);

            return await firebaseMessaging.SendAsync(fcmMessage);```

Thanks!

**Comment by hiranya911** [comment]
Can you provide a simplified example with literal values instead of variables?

I've tried the following, and that seems to work fine:

```
       [Fact]
        public async Task Send2()
        {
            var message = new Message()
            {
                Topic = "foo-bar",
                Apns = new ApnsConfig()
                {
                    Aps = new Aps()
                    {
                        ContentAvailable = true,
                        Badge = 42,
                        Sound = "test",
                    },
                },
            };
            message.Apns.CustomData = new Dictionary<string, object>()
            {
                { "test", "foo" },
            };
            var id = await FirebaseMessaging.DefaultInstance.SendAsync(message, dryRun: true);
            Assert.True(!string.IsNullOrEmpty(id));
            Assert.Matches(new Regex("^projects/.*/messages/.*$"), id);
        }
    }
```

**Comment by hiranya911** [comment]
I did get the mentioned error for the following message:

```
           var message = new Message()
            {
                Topic = "foo-bar",
                Apns = new ApnsConfig()
                {
                    Aps = new Aps()
                    {
                        ContentAvailable = false,
                        Badge = null,
                        Sound = string.Empty,
                    },
                },
            };
```

But in this case the error is to be expected, since the Aps dictionary does not contain any meaningful data.

**Comment by albernhagen** [comment]
Thanks for the quick response @hiranya911 !  I really appreciate it.

This is in a common service so the parameters have varied and I don't currently know the exact combination of parameters that has caused it.  What is considered meaningful data for the APS dictionary?  E.g. how do I know when I should or shouldn't include data in there based on ContentAvailable, Badge, and Sound?  Our default values for these are:

```Aps = new Aps()
                    {
                        ContentAvailable = false,
                        Badge = null,
                        Sound = "default",
                    },```

And a mostly unrelated question, what is the difference between message.Apns.Data and message.Apns.Aps.Data?

**Comment by hiranya911** [comment]
* ContentAvailable only makes sense when set to true (default is false). When false, the corresponding integer value it not included in the aps dictionary.
* Similarly, a null value for Badge is not sent to the backend (default is also null). 
* Sound should also be not null or empty to be included in the aps dictionary (default is null).

Here's an example that shows how CustomData get serialized:

```
new ApnsConfig()
{
  Aps = new Aps()
  {
    CustomData = new Dictionary(){ {"key1", "value1} },
  }
 CustomData = new Dictionary(){ {"key2", "value2} },
}
``` 

This gets serialized as:

```
{
  "aps": {
    "key1": "value1"
  },
  "key2": "value2"
}
```

**Comment by albernhagen** [comment]
Thanks for the info, that's super helpful.  The only other question I have is if `sound = "default"`, is that meaningful?

**Comment by hiranya911** [comment]
@albernhagen, yes that does make sense. I just tested that `Sound = "default"` works fine, when it is the only thing included in `Aps`.

**Comment by albernhagen** [comment]
Great, thanks for all of the info @hiranya911 .  I'll close this out.

**Comment by albernhagen** [comment]
Hey @hiranya911 - While I have your attention, I had one more question I'm hoping you can answer.  Is there a way using the .NET SDK to send messaging channel style commands instead of sending through APNS?

**Comment by hiranya911** [comment]
I don't think so. The SDK currently exposes all the messaging functionality supported by the FCM backend service. But feel free to file a feature request at https://support.google.com/firebase/contact/support?page=bug_or_feature so that the FCM team can take a look and see if this is something we can support.

**Comment by tamngonesv030** [comment]
I had the same problem, Firebase Admin SDK version 1.9.0 for .NET can't push notification to iOS.
How to I can fix it?

**Comment by hiranya911** [comment]
@tamngonesv030 file a support request with details about your project, code and configuration. Nothing that can be done in this repo regarding your issue.
