### ISSUE TITLE
Mute push notification׳s sound is not documented

### ISSUE THREAD

**Issue by msmadja** [firebase/firebase-admin-dotnet#48]
I’m trying to use this library and I tried to find how to mute the sound of the push notification at all. I saw in the APS We have option to define sound as string but in the API I saw sound true/false. Is this missing in this lib. I didn’t find these in the documentations.

**Comment by hiranya911** [comment]
Sound is accepted as a string by APNs: https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW5

> Include this key when you want the system to play a sound. The value of this key is the name of a sound file in your app’s main bundle or in the Library/Sounds folder of your app’s data container. If the sound file cannot be found, or if you specify defaultfor the value, the system plays the default alert sound.
>
> For details about providing sound files for notifications; see Preparing Custom Alert Sounds.

And therefore `Aps.Sound` is a string property in our API: https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/aps#class_firebase_admin_1_1_messaging_1_1_aps_1abf62013b8f49cbe6494e1c1a162d427d

We also have a `CriticalSound` type that maps to the critical alert configuration of APS: https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/critical-sound.html#class_firebase_admin_1_1_messaging_1_1_critical_sound

**Comment by msmadja** [comment]
@hiranya911 Thank you for your response. I saw this documentation but there’s no reference to how to mute the sound of the push notification.

**Comment by msmadja** [comment]
@hiranya911 is it possible to mute the sound of the push notification from the server side? How can I do it?

**Comment by hiranya911** [comment]
You need to figure out how to do that in APNs, and then pass the appropriate flag in `Aps`. Note that `Aps` has a `CustomData` field, which allows passing arbitrary key-value pairs.

**Comment by msmadja** [comment]
@hiranya911 thank you very much for your help.
