### ISSUE TITLE
Is FirebaseApp Instance Singleton?

### ISSUE THREAD

**Issue by shaishavs** [firebase/firebase-admin-dotnet#50]
I would like to know whether an Instance of `FirebaseApp` returned by `FirebaseApp.Create()` method Singleton? 
If not, what is the cost of creating high number of instances of it? I am currently developing for Push Notifications using FCM. And any sample code available where the SDK is used with Service account authentication and FCM?

Reference code:
```
public void SendPushNotification()
        {
            var firebaseApp =
                FirebaseApp.Create(new AppOptions
                {
                    Credential = GoogleCredential.FromFile("path/to/service/account/file.json")
                });

            var firebaseMessaging = FirebaseMessaging.GetMessaging(firebaseApp);

            var message = new Message
            {
                Data = new Dictionary<string, string>
                {
                    { "Test", "Test" }
                },
                Token = ""
            };

            var response = firebaseMessaging.SendAsync(message);
        }
```

**This will be called each time there's a new notification for each user.**

**Comment by hiranya911** [comment]
Yes they are singletons keyed by names.

Please use Stackoverflow for this type of questions.

**Comment by shaishavs** [comment]
Thank you. Yes, I will use SO.

Can you tell the session expiration time i.e how long FirebaseApp stays authenticated once an instance is created? I have looked up at many documentations but couldn't find anything.
