### ISSUE TITLE
customAttributes size limitation is calculated with UTF-16, but it is UTF-8

### ISSUE THREAD

**Issue by ChristopherLenz** [firebase/firebase-admin-dotnet#52]
If the byte-count is calculated with Unicode (UTF-16), it needs 2 bytes per character. The Java and Golang SDK use UTF-8 for that. This way these SDK's are able to store 1000 characters, whereas the dotnet SDK can only store 500 characters.

Can be found in **CheckCustomClaims**-method of **UserRecord**-class.

`
var customClaimsString = SerializeClaims(customClaims);
var byteCount = Encoding.Unicode.GetByteCount(customClaimsString);
if (byteCount > 1000)
{
    throw new ArgumentException($"Claims have to be not greater than 1000 bytes when serialized");
}
`

**Comment by hiranya911** [comment]
Good catch @ChristopherLenz. We can fix it for an upcoming release. You're also welcome to provide a pull request.
