### ISSUE TITLE
CollapseKey is set by default

### ISSUE THREAD

**Issue by RomanHubyak** [firebase/firebase-admin-dotnet#54]
Hello!

When I send a message client (Android app) receives it with CollapseKey.
The issue is when client returns online it receives only last message.

The code below sends message:

````
            var message = new Message
            {
                Data = new Dictionary<string, string>
                {
                    { AppConstants.Fcm.PAGE_ID, page.Id.ToString() },
                    { AppConstants.Fcm.IMAGE_URL, page.ImageUrl },
                    { AppConstants.Fcm.MEDIA_URL, page.MediaUrl },
                    { AppConstants.Fcm.TITLE, page.Title },
                    { AppConstants.Fcm.PAGE_URL, page.Url }
                },
                Topic = AppConstants.Fcm.NEWS_TOPIC
            };

            await FirebaseMessaging.DefaultInstance.SendAsync(message);
````

**Comment by RomanHubyak** [comment]
![image](https://user-images.githubusercontent.com/46841287/57585142-c94ecf80-74ec-11e9-9680-5c70b72c0fe9.png)
The received message.

**Comment by hiranya911** [comment]
That seems to be auto inserted by the FCM service. @chong-shao can you take a look?

**Comment by chong-shao** [comment]
Sorry for the delay in reply. FCM service only sets collapseKey when it's present in the request. @RomanHubyak , could you file a support case to Firebase if this issue still occurs? We can start there and ask for more information from you to debug.
