### ISSUE TITLE
UpdateUser for all properties

### ISSUE THREAD

**Issue by ChristopherLenz** [firebase/firebase-admin-dotnet#55]
At the moment there is only one update-function "**SetCustomUserClaimsAsync**". The internal called "**UpdateUserAsync**" from UserManager is capable to update all properties from the **UserRecord**.
It makes sense to delegate the generic "UpdateUserAsync"-method and make it usable in the "**FirebaseAuth**"-class.

Similar to the Java-SDK: https://github.com/firebase/firebase-admin-java/blob/55d403f20aabe4deb58e6b4dfc2592e6589f7339/src/main/java/com/google/firebase/auth/FirebaseAuth.java#L714-L741

**Comment by hiranya911** [comment]
Fixed in #70
