### ISSUE TITLE
"UpdateUser"-method used by "SetCustomUserClaimsAsync" throws "MISSING_LOCAL_ID"

### ISSUE THREAD

**Issue by ChristopherLenz** [firebase/firebase-admin-dotnet#56]
The serialized "UserRecord" JSON uses the property-names of the "UserRecord"-class. This is wrong and has to be remapped.

Currently:
`{
   "Uid":"40MgueENCLft6rl5Zs4Et0FuiQF3",
   "ProviderId":"firebase",
   "EmailVerified":false,
   "Disabled":false,
   "TokensValidAfterTimestamp":0,
   "customAttributes":"{\"Roles\":[\"AAA\",\"BBB\"]}"
}`

But correct properties would be:
- localId
- email
- disableUser

Edit: ahh I see that you have prepared a pull-request with fixes for that.

**Comment by hiranya911** [comment]
Yes, this was correct in the last release: https://github.com/firebase/firebase-admin-dotnet/blob/31e55ef09ccf50f95cc2dd36d5868228ba320163/FirebaseAdmin/FirebaseAdmin/Auth/UserRecord.cs#L37-L49

But since then it has broken in the master branch. #53 should fix it.

**Comment by hiranya911** [comment]
This fix was released in 1.5.0
