### ISSUE TITLE
The caller does not have permission [403] with firebase cloud messaging.

### ISSUE THREAD

**Issue by redplane** [firebase/firebase-admin-dotnet#59]
Hi, 

I'm using `ASP.Net Core` as my back-end for my project.
In my project. I need to send push notifications to my clients.

I registered `FirebaseApp` and `FirebaseMessaging` as dependency injection components.

Here is my code:

```
/// <summary>
        /// Setup firebase application.
        /// </summary>
        protected static void SetupCloudApplication(IServiceCollection services, IConfiguration configuration)
        {
            // Setup firebase app.
            services.AddSingleton(x =>
            {
                var options = new AppOptions();
                var cloudMessagingSettings = x.GetService<IOptions<FirebaseCloudMessagingSettingModel>>().Value;
                if (cloudMessagingSettings == null)
                    throw new Exception("No cloud message settings have been found");

                // Find hosting environment.
                var hostingEnvironment = x.GetService<IHostingEnvironment>();

                // Find credential settings file.
                var credentialFile = Path.Combine(hostingEnvironment.ContentRootPath,
                    cloudMessagingSettings.CredentialFile);

                options.Credential = GoogleCredential.FromFile(credentialFile)
                    .CreateScoped("https://www.googleapis.com/auth/firebase.messaging", "https://www.googleapis.com/auth/cloud-platform");

                options.ProjectId = cloudMessagingSettings.ProjectId;
                options.ServiceAccountId = cloudMessagingSettings.ServiceAccountId;
                return FirebaseApp.Create(options);
            });

            // Setup cloud messaging.
            services.AddScoped(x =>
            {
                var cloudApp = x.GetService<FirebaseApp>();
                return FirebaseMessaging.GetMessaging(cloudApp);
            });
        }

```

Following [this tutorial](https://firebase.google.com/docs/cloud-messaging/auth-server), I can get a `service account` json file. I downloaded that file and saved into my web project.

DI components were OK, my application started successfully.
When I tried sending a push message to my clients. I received an error:

**2019-05-25 16:13:13.546 +08:00 [Error] Google.Apis.Requests.RequestError
The caller does not have permission [403]
Errors [
	Message[The caller does not have permission] Location[ - ] Reason[forbidden] Domain[global]
]**

What was wrong with my code ?

Thanks

**Comment by hiranya911** [comment]
Code looks ok, although you have a lot of boilerplate I'm not familiar with, so I can't say for sure. I'd try removing the `CreateScoped()` API call, since the SDK adds all the scopes it requires by default.

The other thing to verify is that the project ID you specify corresponds to the service account you're using to authenticate with.

```
options.ProjectId = cloudMessagingSettings.ProjectId;
```

**Comment by hiranya911** [comment]
Have you figured this out? If not can you provide a minimal and complete repro for us to try out?

**Comment by redplane** [comment]
Sorry for my late reply.
It was my mistake. I put wrong appId into the firebase cloud message, that's why I got 403 .
The credential I copied wasn't from Firebase cloud console.
