### ISSUE TITLE
Firebase 404 NOT_FOUND

### ISSUE THREAD

**Issue by kevingoos** [firebase/firebase-admin-dotnet#73]
I am trying to implement firebase admin into ASP.NET core but I am missing something...
Everytime I run my code I get the following error:

```
Response status code does not indicate success: 404 (NotFound)
{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "errors": [
      {
        "message": "Requested entity was not found.",
        "domain": "global",
        "reason": "notFound"
      }
    ],
    "status": "NOT_FOUND"
  }
}
```
The code that I am running:
```
var message = new Message
{
    Token = fcmToken,
    Data = new Dictionary<string, string>
    {
        {"title", notification.Title},
        {"body", notification.Message},
        {"channel", notification.Channel},
        {"level", ((int)notification.Level).ToString()},
        {"link", notification.Link}
    }
};

try
{
    var fcmResult = await FirebaseMessaging.DefaultInstance.SendAsync(message);
}
catch (Exception ex)
{

}
```
Registration:
```
if (FirebaseApp.DefaultInstance == null)
{
    FirebaseApp.Create(new AppOptions
    {
        Credential = GoogleCredential.FromJson(Settings.Default.Firebase_Server_Auth)
    });
}
```
Github link: https://github.com/kevingoos/FirebaseAdminTest
Stackoverflow: https://stackoverflow.com/questions/56499904/firebaseadmin-messaging-returning-404-not-found

**Comment by hiranya911** [comment]
This happens when the token is invalid/expired or does not belong to the same project as the credentials used to initialize the Admin SDK.

**Comment by chrisparkeronline** [comment]
Maybe you can help me. I'm getting the same error after my code working for a few days. I'm downloading the json file from the "Settings"/"Service accounts" area of firebase console. I click the "Generate new private key" button and it gives me the file. Add that to my project and load it. FYI i'm doing this in a Azure Function but it's pretty much the same as your web code.

Am I generating the json file wrong or it something else?

**Comment by Gokaysim** [comment]
> This happens when the token is invalid/expired or does not belong to the same project as the credentials used to initialize the Admin SDK.

I have tested it. Yes, thats the problem but not a solution. In my architectural design, I don't want to send Notification from my controller. Is there anyone working on a PR or something. Maybe I can help too

**Comment by alexsandro-xpt** [comment]
@hiranya911 Why the client token expire?
Can I know when all client token will expire to refresh a new token?

**Comment by arnoldsmyth** [comment]
@chrisparkeronline did you ever solve this? I am at my wits end trying to figure this out. I downloaded the JSON file as you mentioned by clicking the "Generate new private key" button. I have done this on two different Firebase projects. The first works fine - and the second give me the 404 error.

**Comment by hiranya911** [comment]
It's most likely a matter of expired or invalid FCM registration token. Make sure the token is up-to-date (this needs to be handled at the client side), and the token belongs to the same project as the service account.

**Comment by delmatrios** [comment]
facing the same problem still my token is up to date and no change

**Comment by memukeshsahoo** [comment]
If the token is valid and still you are getting the issue then try 

` var firebaseresponse = await FirebaseMessaging.DefaultInstance.SendEachForMulticastAsync(message);

 if (firebaseresponse.FailureCount > 0)
 {
     _logger.LogWarning("Failed to send to {FailureCount} tokens", firebaseresponse.FailureCount);
     for (int i = 0; i < firebaseresponse.Responses.Count; i++)
     {
         var result = firebaseresponse.Responses[i];
         if (!result.IsSuccess)
         {
             _logger.LogError("Failed to send to token {Token}: {Error}",
                 message.Tokens[i], result.Exception?.Message);
         }
     }
 }`
