### ISSUE TITLE
FCM - Too dificult to work with the response error codes

### ISSUE THREAD

**Issue by theberserker** [firebase/firebase-admin-dotnet#75]
The `FirebaseException` seems a bit oversimplified by just wrapping the `HttpRequestException` and also not aligned with https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode

Error code enums should be returned somewhere. What I have to at this point is to look up for status code (e.g. "[503]") in the `FirebaseException.Message`, which of course doesn't work in the case of `UNSPECIFIED_ERROR` from ErrorCode documentation.

For starters, maybe you could at least state what to look for at `UNSPECIFIED_ERROR` type of response. Propagating the error codes is important for exponential backoff implementations.

**Comment by hiranya911** [comment]
Closing as a duplicate of #45.

No FCM operation actually returns in `UNSPECIFIED_ERROR` as far as I know. None of the other Admin SDK implementations handle it explicitly.

**Comment by bilaljaved786** [comment]
Exception thrown: 'FirebaseAdmin.Messaging.FirebaseMessagingException' in System.Private.CoreLib.dll

am getting this issue @hiranya911
