### ISSUE TITLE
Implementation of InstanceIdClient (FCM topic management) is missing

### ISSUE THREAD

**Issue by theberserker** [firebase/firebase-admin-dotnet#83]
The title should be quite self-explanatory. I'm looking at java SDK, where FCM topic management functionality is available under `InstanceIdClient`, methods `subscribeToTopic` and `unsubscribeFromTopic`. Can this feature be expected anytime soon by the Firebase team?

**Comment by hiranya911** [comment]
Not unless somebody in the community contributes the code. The Firebase team will eventually get to it, but it won't be anytime soon.
