### ISSUE TITLE
Firebase admin proxy issue 

### ISSUE THREAD

**Issue by mirosama** [firebase/firebase-admin-dotnet#85]
Note: my firebase code is running on container behind the proxy and in my code i am configurating it like in image below .

![image](https://user-images.githubusercontent.com/25574071/60336164-25ed4780-99d2-11e9-97e1-5ba990247d24.png)

Note: I used curl command to send notification using proxy and it works like a charm 

but firebase admin code gives this error 

{"EntryDate":"Fri Jun 28 09:34:42 +00:00 2019","Level":"ERROR","Message":{"body":"FirebaseAdmin.FirebaseException: Error while calling the FCM service. ---> System.Net.Http.HttpRequestException: No such device or address ---> System.Net.Sockets.SocketException: No such device or address\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at Google.Apis.Http.ConfigurableMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.ExecuteAsync(TokenRequest request, HttpClient httpClient, String tokenServerUrl, CancellationToken taskCancellationToken, IClock clock)\n   at Google.Apis.Auth.OAuth2.ServiceAccountCredential.RequestAccessTokenAsync(CancellationToken taskCancellationToken)\n   at Google.Apis.Auth.OAuth2.TokenRefreshManager.RefreshTokenAsync()\n   at Google.Apis.Auth.OAuth2.TokenRefreshManager.ResultWithUnwrappedExceptions[T](Task`1 task)\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\n   at System.Threa
--
  | ding.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\n--- End of stack trace from previous location where exception was thrown ---\n   at Google.Apis.Auth.OAuth2.TokenRefreshManager.GetAccessTokenForRequestAsync(CancellationToken cancellationToken)\n   at Google.Apis.Auth.OAuth2.ServiceAccountCredential.GetAccessTokenForRequestAsync(String authUri, CancellationToken cancellationToken)\n   at Google.Apis.Auth.OAuth2.ServiceCredential.InterceptAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at Google.Apis.Http.ConfigurableMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Google.Apis.Requests.BatchRequest.ExecuteAsync(CancellationToken cancellationToken)\n   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendBatchRequestAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)\n   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendAllAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at FirebaseAdmin.Messaging.FirebaseMessagingClient.SendAllAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)\n   at FirebaseAdmin.Messaging.FirebaseMessaging.SendAllAsync(IEnumerable`1 messages, Boolean dryRun, CancellationToken cancellationToken)\n   at FirebaseAdmin.Messaging.FirebaseMessaging.SendAllAsync(IEnumerable`1 messages, Boolean dryRun)\n   at FirebaseAdmin.Messaging.FirebaseMessaging.SendAllAsync(IEnumerable`1 messages)\n   at PushNotificationsService.FirebaseHandler.FirebaseMessageComposer.SendMessageBatch(List`1 messages) in /opt/app-root/src/Pu

**Comment by NecromancerKing** [comment]
I am crippled by exact same probelm. Any idea how to configure http proxy correctly with firebase admin in .Net?

**Comment by hiranya911** [comment]
It's the `GoogleCredential` that is failing to connect to the remote server. You have to also pass your proxy configuration to the credential. See the example at https://medium.com/google-cloud/accessing-google-cloud-apis-though-a-proxy-fe46658b5f2a

**Comment by mirosama** [comment]
i am passing a JSON file with all the credentials , it is working fine in a environment that doesnt require proxy but it gives error when i try to run in a environment that requires proxy . curl and http direct call is working fine even in proxy environment . It is an http proxy without any credentials just URL . what i am exactly missing ?

**Comment by hiranya911** [comment]
You need to pass your `ProxyHttpClientFactory` to `GoogleCredential` as well. See the example I referenced above.

**Comment by c0rrectanswer** [comment]
The combination of GoogleCredential.FromJson and 
passing your proxy configuration to the GoogleCredential won't work.

**Comment by c0rrectanswer** [comment]
You need to do ... this ... and that ... as well, how to do that?
```
var gCredentials = JsonConvert.DeserializeObject<Dictionary<string, string>>(jsonCredentialsString); // see attached image on how to get this json credentials string
WebProxy webproxy = new WebProxy()
{
    Address = (new UriBuilder("http", "proxy.my", 6666)).Uri,
    BypassProxyOnLocal = true,
    UseDefaultCredentials = true
};
ServiceAccountCredential serviceAccountCredential = new ServiceAccountCredential(
    new ServiceAccountCredential.Initializer(gCredentials.GetValueOrDefault("client_email"))
    {
        HttpClientFactory = new ProxyHttpClientFactory(webproxy)
    }.FromPrivateKey(gCredentials.GetValueOrDefault("private_key")));
); 
```
How to pass your ProxyHttpClientFactory to GoogleCredential?
```
ServiceAccountCredential serviceAccountCredential = new ServiceAccountCredential(
    new ServiceAccountCredential.Initializer(gCredentials.GetValueOrDefault("client_email"))
    {
        HttpClientFactory = new ProxyHttpClientFactory(webproxy)
    }.FromCertificate(certificate) // or alternatively .FromPrivateKey(gCredentials.GetValueOrDefault("private_key")));
); 
```
How to pass your ProxyHttpClientFactory to FirebaseAdmin FirebaseApp.Create AppOptions?
```
var app = FirebaseApp.Create(new AppOptions()
{
    Credential = GoogleCredential.FromServiceAccountCredential(serviceAccountCredential),
    HttpClientFactory = new ProxyHttpClientFactory(webproxy),
    ServiceAccountId = serviceAccountCredential.Id,
    ProjectId = gCredentials.GetValueOrDefault("project_id")
});
List<Message> list = new List<Message>()
{
    new Message()
    {
        Token = "token_here",
        Notification = new Notification()
        {
            Body = "random body: " + DateTime.Now.ToShortDateString() + " " + DateTime.Now.ToShortTimeString(),
            Title = "t[" + DateTime.Now.ToShortTimeString() + "]"
        }
    }
};
FirebaseMessaging.DefaultInstance.SendAllAsync(list)
```
![image](https://user-images.githubusercontent.com/52475928/60561000-9efaef00-9d84-11e9-811b-823d64e5cfed.png)

**Comment by c0rrectanswer** [comment]
You need to do ... this ... and that ... as well, how to do that?
```
var gCredentials = JsonConvert.DeserializeObject<Dictionary<string, string>>(jsonCredentialsString); // see attached image on how to get this json credentials string
WebProxy webproxy = new WebProxy()
{
    Address = (new UriBuilder("http", "proxy.my", 6666)).Uri,
    BypassProxyOnLocal = true,
    UseDefaultCredentials = true
};
ServiceAccountCredential serviceAccountCredential = new ServiceAccountCredential(
    new ServiceAccountCredential.Initializer(gCredentials.GetValueOrDefault("client_email"))
    {
        HttpClientFactory = new ProxyHttpClientFactory(webproxy)
    }.FromPrivateKey(gCredentials.GetValueOrDefault("private_key")));
); 
```
How to pass your ProxyHttpClientFactory to GoogleCredential?
```
ServiceAccountCredential serviceAccountCredential = new ServiceAccountCredential(
    new ServiceAccountCredential.Initializer(gCredentials.GetValueOrDefault("client_email"))
    {
        HttpClientFactory = new ProxyHttpClientFactory(webproxy)
    }.FromPrivateKey(gCredentials.GetValueOrDefault("private_key")));
); 
```
How to pass your ProxyHttpClientFactory to FirebaseAdmin FirebaseApp.Create AppOptions?
```
var app = FirebaseApp.Create(new AppOptions()
{
    Credential = GoogleCredential.FromServiceAccountCredential(serviceAccountCredential),
    HttpClientFactory = new ProxyHttpClientFactory(webproxy),
    ServiceAccountId = serviceAccountCredential.Id,
    ProjectId = gCredentials.GetValueOrDefault("project_id")
});
```
How to fire the message?
```
List<Message> list = new List<Message>()
{
    new Message()
    {
        Token = "token_here",
        Notification = new Notification()
        {
            Body = "random body: " + DateTime.Now.ToShortDateString() + " " + DateTime.Now.ToShortTimeString(),
            Title = "t[" + DateTime.Now.ToShortTimeString() + "]"
        }
    }
};
FirebaseMessaging.DefaultInstance.SendAllAsync(list)
```
![image](https://user-images.githubusercontent.com/52475928/60561222-69a2d100-9d85-11e9-9da1-3a52fb2ec14f.png)

**Comment by c0rrectanswer** [comment]
Testing code for environment with proxy without FirebaseAdmin
```
Message message = messages.First();

var webproxy = new WebProxy((new UriBuilder("http", "proxy.my", 6666)).Uri, true);
var httpclienthandler = new HttpClientHandler() 
{
	Proxy = webproxy,
	UseProxy = true,
	UseDefaultCredentials = true
};

var request = new HttpRequestMessage(HttpMethod.Post, "https://fcm.googleapis.com/fcm/send");
request.Headers.TryAddWithoutValidation("Authorization", "key=key_here");

string json = "{\"to\":\"token_here\",\"notification\":{\"body\":\"random text\",\"title\":\"random title\",\"badge\":5}}";
request.Content = new StringContent(json, Encoding.UTF8, "application/json");

using (var client = new HttpClient(handler: httpclienthandler, disposeHandler: true))
{
	var result = await client.SendAsync(request);
	await result.Content.ReadAsStringAsync();
}
```

**Comment by graphicsxp** [comment]
Where is ProxyHttpClientFactory coming from  ?  I cannot find it.

**Comment by hiranya911** [comment]
That's a class you implement by extending the `HttpClientFactory`.
