### ISSUE TITLE
Could you please provide pure dll that could be used in unity PC platform?

### ISSUE THREAD

**Issue by Thaina** [firebase/firebase-admin-dotnet#86]
I just want to write unity editor extension that could administering firebase system in the editor. Such as minting token to login as any ID for testing process

But unity cannot use nuget officially. So if there would be pure dll and dependency or unitypackage that could easily include in the project that would be great

Is it possible?

**Comment by hiranya911** [comment]
This sounds like a client-side use case, but I don't know enough about Unity to be certain. We usually have a strict policy against not supporting client-side development with Admin SDKs.

@stewartmiles what do you think?

@Thaina can you build your own DLLs from the source for your work? I'm not sure how to even publicly distribute a DLL.

**Comment by Rohansi** [comment]
The Unity Editor is development time so not client-side. You can try using this: https://assetstore.unity.com/packages/tools/utilities/nuget-for-unity-104640

Or, if you just want a DLL, you can [download the package directly from NuGet](https://www.nuget.org/packages/FirebaseAdmin/) (see right side) and unzip it to find the DLL.

**Comment by bjustice-sympatient** [comment]
Nuget for Unity was quite messy when I tried it for a different Nuget package.
It also downloads all ".net core SDK" dependencies, which results in huge unnecessary downloads.

One possible way (used by other libraries as well) is to build a .dll file and distribute it as a "release" in github.

The only tricky part here would be handling transitive dependencies.
@Thaina have you investigated in the transitive dependencies?

**Comment by Thaina** [comment]
@bjustice-sympatient I haven't done anything about this since then, I just have my own server as proxy because I don't want to mess with nuget in unity too

**Comment by hiranya911** [comment]
@a-maurice assigning to you for a quick look.

**Comment by a-maurice** [comment]
Hi all,

I lead the Firebase for Unity SDKs, https://firebase.google.com/docs/unity/setup.  We do offer some of the Firebase services to work in Desktop via the editor, though not all, and are instead more focused on building for mobile platforms through Unity.  If there are specific features you would like to add for the Firebase for Unity SDKs, you can always issue a ticket here: https://github.com/firebase/quickstart-unity.
