### ISSUE TITLE
Delete Users

### ISSUE THREAD

**Issue by rachelward9** [firebase/firebase-admin-dotnet#9]
It would be rad if you could support deleting users! :)

**Comment by hiranya911** [comment]
We want to eventually add all of our [user management APIs](https://firebase.google.com/docs/auth/admin/manage-users) to this SDK. Would you be willing to provide us a pull request (perhaps starting with just get and delete operations)? We'd be happy to help with design and code reviews.

**Comment by levimatheri** [comment]
@hiranya911 I just submitted a PR for this and get user. I'm new to the .NET Firebase SDK but have used Firebase in Flutter and want to contribute. Cheers! :+1:

**Comment by hiranya911** [comment]
Fixed in #53
