### ISSUE TITLE
Proposal: Implementation of InstanceIdClient (FCM topic management)

### ISSUE THREAD

**Issue by Leo-Mepham** [firebase/firebase-admin-dotnet#93]
As per issue #83, I'm working on a conversion to C# from the Java InstanceIdClient to allow tokens to be added and removed from topics. 

Guidelines said I should post here first, although I'm currently just working through unit & integration tests :)

Let me know if there's anything I should be aware of or bear in mind.

**Comment by hiranya911** [comment]
I'll dedupe this with #83 for easier tracking.
