### ISSUE TITLE
Heads up notification not displaying in Android 7.1

### ISSUE THREAD

**Issue by Kiruchi** [firebase/firebase-admin-dotnet#96]
I am trying to send a heads up notification to a specific topic on a variety of devices.
I do have devices on Android 7.1 and +.

Everything is ok when I try to send a notification to Android 7.2+. 
Notification channels are used and I created a channel with an appropriate importance so the heads up notification is showing properly.

On this [link](https://developer.android.com/guide/topics/ui/notifiers/notifications) we can see :

> Example conditions that might trigger heads-up notifications include the following:
> 
> - The user's activity is in fullscreen mode (the app uses fullScreenIntent).
> - The notification has high priority and uses ringtones or vibrations on devices running Android 7.1 (API level 25) and lower.
> - The notification channel has high importance on devices running Android 8.0 (API level 26) and higher.

So a heads up notification on Android 7.1  seems to require high priority and a ringtone or vibration.

I need to have a single code to send notifications to Android 7.1 and Android 7.1+ so here is the code I wrote : 

```c#
var message = new FirebaseAdmin.Messaging.Message()
{
    Topic = "my-topic",
    Webpush = new WebpushConfig()
    {
        Notification = new WebpushNotification()
        {
            Renotify = true,
            RequireInteraction = true,
            Silent = false,
            Vibrate = new int[] { 500, 500, 500, 500, 500 },
        }
    },
    Android = new AndroidConfig()
    {
        TimeToLive = new TimeSpan(0, 30, 0),
        Priority = Priority.High,
        Notification = new AndroidNotification()
        {
            Tag = "my-tag",
            Title = "my title",
            Body = "my body",
            ChannelId = "my-channel",
            Sound = "default"
        }
    }
};

// Send a message to the devices subscribed to the provided topic.
await FirebaseMessaging.DefaultInstance.SendAsync(message).ConfigureAwait(false);
```

I send a Sound as "default" in the Android config and a high priority.
When my app is not opened, I receive the notification but it stays in the tray and does not show up as heads-up.
Why isn't the notification showing up as heads-up ? Is the "default" value for Sound supported ?

**Comment by chong-shao** [comment]
Hi @Kiruchi ,  the Priority in AndroidConfig is an FCM concept that controls when the message is delivered. It does not translate to Android priority. 

The current reference for this field in https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages is confusing. We will update the reference soon to clarify the concept.

**Comment by Kiruchi** [comment]
So is there any parameter for Android priority ? Or a way of sending a message which will be in heads up on Android 7.1 ?

**Comment by chong-shao** [comment]
Hi @Kiruchi , for now there's no way to directly send a heads up message on Android 7.1. A solution would be to update the client-side code to accept a data message and convert it to a displayed notification on the client side. 

We are working on a solution to provide more parameters in FCM API so this can be supported.
